### ISSUE TITLE
Split LB tutorial into LB, polymer and Langevin simulation tutorials

### ISSUE THREAD

**Issue by jngrad** [espressomd/espresso#3939] opened 2020-10-08 11:04 UTC
The LB tutorial introduces the Flory theory of polymers, the Rouse regime (implicit solvent) and the Zimm regime (LB fluid). The only difference between Langevin Dynamics and lattice-Boltzmann is the absence resp. presence of the second term in the Kirkwood-Zimm equation of the diffusion coefficient of polymers:

<img src="https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle%20D%3D%5Cfrac%7BD_0%7D%7BN%7D%20%2B%20%5Cfrac%7Bk_B%20T%7D%7B6%20%5Cpi%20%5Ceta%20%7D%20%5Cleft%5Clangle%20%5Cfrac%7B1%7D%7BR_h%7D%20%5Cright%5Crangle" alt=" D=(D_0)/(N) + \frac{k_B T}{6 \pi \eta } \left\langle (1)/(R_h) \right\rangle" height=40>

We could move part 2 and 3 to a self-contained polymer tutorial. The part 3 can be switched from LD to LB by changing a variable at the beginning of the file (both versions are tested in CI).

**Comment by jngrad** [comment] 2020-10-08 14:45
The resulting LB tutorial could get an additional part where we simulate particles falling in a vacuum vs. in a LB fluid, to reproduce the video from the "ESPResSo features" lecture.

**Comment by schlaicha** [comment] 2020-12-17 12:52
I've split the tutorial in #4052 and will briefly check the physics with Christian later.
For the suggested LB tutorial is the script somewhere around? Is this at all realistic to have it interactively in a notebook?

**Comment by schlaicha** [comment] 2020-12-18 14:03
Offline discussion with Christian:
- Further split into a Langevin dynamics tutorial (now polymer part 1)
- add density-dependent diffusion ($\sim N^3/2$?)
- use more appropriate names for LB tutorial (theory and Poiseuille flow instead of part 1 and part 2)
- Check is visualization of the sedimentation can be done (see my note above). @jngrad can you comment on this?
Updating issue title and closing PR until this is added.

**Comment by schlaicha** [comment] 2020-12-18 14:07
I cannot change the issue title, can somebody either give me the rights (assign?) or change it correspondingly?

**Comment by jngrad** [comment] 2020-12-18 14:12
@schlaicha You should now be able to change the title.

I don't know if there is a script for the sedimentation visualization (the video was probably made in the Tcl days).

**Comment by schlaicha** [comment] 2020-12-18 14:18
> @schlaicha You should now be able to change the title.

No, also I cannot add myself as assignee.

**Comment by jngrad** [comment] 2020-12-18 14:22
ok, maybe GitHub prevents users from changing other people's ticket titles... I can take care of that, what title do you propose?

Unfortunately, we cannot give you more rights, because the [next permission level is Triage](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level), which would allow you to merge approved PRs by editing the labels.

**Comment by schlaicha** [comment] 2020-12-18 14:26
I would just change according to the PR: "Split LB tutorial into LB, polymer and Langevin simulation tutorial"

**Comment by biermanncarl** [comment] 2021-05-31 18:42
>     * add density-dependent diffusion ($\sim N^3/2$?)

According to [Wikipedia](https://en.wikipedia.org/wiki/Diffusion#Diffusion_coefficient_in_kinetic_theory_of_gases), D should behave like 1/P, which is proportional to 1/rho. Unfortunately, I couldn't get this scaling out of a Langevin Dynamics setup. The problem is that kinetic gas theory expects the particles to move in a straight line, while Langevin Dynamics prevents exactly this. Lowering the friction coefficient will render the simulation numerically unstable, i.e. the particles will slowly gain kinetic energy. The only way to deal with this is to lower the time step, which increases computational effort to get useful statistics. Overall I have the impression that using this result in a Langevin Dynamics tutorial has proven to be unfeasible.

**Comment by jngrad** [comment] 2021-08-09 12:47
We need 2 people: one to look at the Langevin tutorial, one to look at the LB tutorial.

**Closed as completed** 2021-08-17 14:17 UTC
Labels: Documentation, CodingDay
