### ISSUE TITLE
Odd difference in statistics between LB CPU and GPU test

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2226] opened 2018-09-04 20:53 UTC
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/37547

possibly due to changes in the in #2220 or #2221.

**Comment by KaiSzuttor** [comment] 2018-09-05 04:29
lb test was only touched in #2221

**Comment by fweik** [comment] 2018-09-05 07:57
Ok. Then either somebody has to look at this again or we just revert #2221, since it only changed test performance.

**Comment by KaiSzuttor** [comment] 2018-09-05 08:49
I can not reproduce the failing lb test on a linux machine...

**Comment by KaiSzuttor** [comment] 2018-09-05 09:09
actually also not on mac neither with python2 nor with python3

**Comment by RudolfWeeber** [comment] 2018-09-05 09:53
I had a closer look. 
Are we prepared to believe that the standard deviation for kT=1.5
is 0.015 for the cpu lb and 0.15 for the gpu lb?
A single measurement is for the entire lb fluid.

Is the expected standard deviation of the temperature known?

**Comment by RudolfWeeber** [comment] 2018-09-05 09:54
I have cleaned up the lb test, but the question is which criterion to use.
Based on the standard deviation estimated from the sample, the lbgpu would bass the 95% confidence interval, but the lb cpu would not because of the much smaller standard deviation.

**Comment by KaiSzuttor** [comment] 2018-09-05 10:02
since the LB thermostat is nothing but a langevin thermostat it should ideally be tested the same way (ideally the langevin thermostat would be used for LB)

**Comment by fweik** [comment] 2018-09-05 10:11
@KaiSzuttor doesn't this concern the LB thermalization, and not the particle coupling?

**Comment by KaiSzuttor** [comment] 2018-09-05 10:15
I'm not sure what @RudolfWeeber is talking about

**Comment by RudolfWeeber** [comment] 2018-09-05 10:20
I'm talking about the fluid temperature, which is calculated
as T \sim node_density *|node_velocity|^2 

The particle temperature (\sim m |v|^2) is not the issue.

**Comment by KaiSzuttor** [comment] 2018-09-05 10:34
another issues with the test: it's not clear to me why we have a different precision for the mass and momentum for CPU and GPU

**Comment by RudolfWeeber** [comment] 2018-12-04 18:51
The temperature fluctuation issue has been resolved. Mass loss has its own ticket. Closing for now.

**Closed as completed** 2018-12-04 18:51 UTC
