### ISSUE TITLE
```copy_v_cs_from_GPU(Utils::Range<ParticleIterator<Cell**, Particle> >)``` seems to make trouble with hip

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#2413] opened 2018-12-12 19:47 UTC
see https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/56529

**Comment by mkuron** [comment] 2018-12-12 22:05
What pull request did this start with? It worked fine last week.

**Comment by mkuron** [comment] 2018-12-13 08:43
I think #2390 fixes it. https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/57294 did not crash.

**Comment by KaiSzuttor** [comment] 2018-12-13 14:03
no, still have issues in #2406:
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/57513

**Comment by mkuron** [comment] 2018-12-13 14:11
Now it only occurs in engine_lb, which makes some sense. It didn't occur in #2390, which means that it was broken by some pull request in the past two weeks.

**Comment by hmenke** [comment] 2018-12-13 20:42
It might be that HIP does not like the strided `memcpy` we are performing in `copy_v_cs_from_GPU`.  

https://github.com/espressomd/espresso/blob/7a485cc49f0cb494ebc0c5b982b6efbcee6a98f1/src/core/cuda_common_cuda.cu#L462-L477

What we are doing here is, instead of calling `memcpy` for each individual particle we are calling `memcpy` of *all* particles at once, but in strides of the first few bits.  That is also the reason why `v_cs` *must* remain the first member in the `CUDA_ParticleParametersSwimming` structure.

https://github.com/espressomd/espresso/blob/7a485cc49f0cb494ebc0c5b982b6efbcee6a98f1/src/core/cuda_interface.hpp#L46-L58

**Comment by mkuron** [comment] 2018-12-13 20:44
That should be fine. Also it used to work, some recent change must have broken it. I won‘t have time to debug it before next week though.

**Comment by mkuron** [comment] 2018-12-17 11:36
It's mysteriously fixed on the current master: https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/57998 . I also couldn't reproduce it on my own machine. Please close this issue for now.

**Closed as completed** 2018-12-17 12:01 UTC
