### ISSUE TITLE
Walberla: LBSlice boundary setter

### ISSUE THREAD

**Issue by reinaual** [espressomd/espresso#4423] opened 2022-01-11 16:42 UTC
The `LBSlice`-class has an issue when setting a boundary.

```python
import espressomd
import espressomd.lb

system = espressomd.System(box_l=[10, 10, 10])
system.time_step = 1.0

lattice = espressomd.lb.LatticeWalberla(n_ghost_layers=1, agrid=1.0)

lbf = espressomd.lb.LBFluidWalberla(lattice=lattice, viscosity=1.0, density=1.0, tau=1.0, agrid=1.0)

system.actors.add(lbf)

lbf[1, :, :].boundary = [1.0, 1.0, 1.0]
```

```
Traceback (most recent call last):
  File "../script/lb_issue.py", line 13, in <module>
    lbf[1, :, :].boundary = [1.0, 1.0, 1.0]
  File "/ssd/areinauer/espresso/rudolf/build/src/python/espressomd/lb.py", line 837, in __setattr__
    raise ValueError(
ValueError: Input-dimensions of 'boundary' array (3,) does not match slice dimensions (1, 10, 10).
```

If i understood the code correctly this happens because `__getattr__` in `LBSlice` calls the property-getter on the fluid node with index `[0, 0, 0]` and looks at the shape of the returned value. The issue is that the result will only be `not None` if and only if the node is already a boundary.

Another issue with the same class is when the boundary is set with a `VelocityBounceBack` object. The attempt to broadcast the object to the correct shape fails.

```python
lbf[1, :, :].boundary = espressomd.lb.VelocityBounceBack([1.0, 1.0, 1.0])
```
```
Traceback (most recent call last):
  File "../script/lb_issue.py", line 13, in <module>
    lbf[1, :, :].boundary = espressomd.lb.VelocityBounceBack([1.0, 1.0, 1.0])
  File "/ssd/areinauer/espresso/rudolf/build/src/python/espressomd/lb.py", line 834, in __setattr__
    value = np.ones(target_shape) * value
TypeError: unsupported operand type(s) for *: 'float' and 'VelocityBounceBack'
```

**Comment by jngrad** [comment] 2022-01-16 23:49
Indeed, that's an oversight on my part. The expected behavior for your MWE is a type error, because velocities should be wrapped inside a `VelocityBounceBack` class. This should be fixed by be7c72cc336ce581e.

**Closed as completed** 2022-01-19 16:19 UTC
Labels: waLBerla
