### ISSUE TITLE
Timeouts in the CI

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#2618] opened 2019-03-20 13:43 UTC
e.g. (times are from the CI)
```
 40/123 Test  #58: virtual_sites_tracers ...................   Passed  247.73 sec
[...]
 54/123 Test #122: lb_density ..............................   Passed  394.11 sec
```
with debug builds I regularly get timeouts (default timeout is 300s) even on a modern machine, this is too slow to be practical.

**Comment by KaiSzuttor** [comment] 2019-03-20 14:22
you mean the tests are too long or we should find out where the performance drop comes from... We knew before merging that LB will be slower

**Comment by KaiSzuttor** [comment] 2019-03-20 14:36
``` bash
82/123 Test  #66: lb ......................................   Passed   13.17 sec
```
with 

``` bash
cmake_params=-DCMAKE_BUILD_TYPE=Debug -DPYTHON_EXECUTABLE=/usr/bin/python2 -DWARNINGS_ARE_ERRORS=ON -DTEST_NP:INT=2  -DWITH_SCAFACOS=ON -DCMAKE_CXX_FLAGS=-Og
```

in https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/88590

How do you know that it is connected to the refactoring?

**Comment by fweik** [comment] 2019-03-20 14:39
I don't, but it is reasonable to assume that it is related? Could also some problem in the CI.

**Comment by fweik** [comment] 2019-03-20 14:46
looks like a CI problem, but the issue still needs to be addressed.

**Comment by fweik** [comment] 2019-03-21 07:48
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/88973 has failed due to timed out LB tests

**Comment by KaiSzuttor** [comment] 2019-03-21 12:48
It seems like whenever I run the tests, the issue is gone :disappointed: 
I don't have the time to run the tests for everybody, so that doesn't seem to be a solution

**Comment by jngrad** [comment] 2019-03-21 15:04
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/89108
```
 70/123 Test  #51: ek_eof_one_species_x ....................***Timeout 300.02 sec
 71/123 Test  #52: ek_eof_one_species_y ....................***Timeout 300.03 sec
 72/123 Test  #53: ek_eof_one_species_z ....................***Timeout 300.02 sec
121/123 Test #119: lb_thermostat ...........................***Timeout 300.02 sec
```

**Comment by fweik** [comment] 2019-04-03 12:08
Master is read again because of this:
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/pipelines/6362

**Comment by KaiSzuttor** [comment] 2019-04-03 12:34
that happens quite often... the tests for the exotic arches fail and nobody notices. The staging branch would probably help here.

**Comment by mkuron** [comment] 2019-04-03 12:47
The staging branch probably wouldn't help. It just would end up not getting automatically merged into the master branch for days until someone noticed.

**Comment by KaiSzuttor** [comment] 2019-04-03 12:50
It helps with respect to having a green master and a documentation that corresponds to the current master.

**Comment by RudolfWeeber** [comment] 2019-04-03 13:05
On Wed, Apr 03, 2019 at 12:35:00PM +0000, Kai Szuttor wrote:
> that happens quite often... the tests for the exotic arches fail and nobody notices. The staging branch would probably help here.
I test-drove Espresso on the native arm processors offered by Amazon EC2 now (a1 instances).
The performance is really bad (10x slower on a single core of a1 compared to my ICP machine).
I don't see the Arm stuff becoming relevant for simulation applications for a while.

In view of our limited resources, we should consider dropping the tests for non-x86 archs until these platforms become relevant for users.
I feel they drawing away attention from issues more relevant to our users.

**Comment by mkuron** [comment] 2019-04-03 13:18
> The performance is really bad 

Amazon's Graviton processor isn't very suitable for pure number crunching (it's optimized for web stuff), so your results are entirely expected. A Cavium ThunderX2 or another Arm CPU targeted at the HPC market should give an entirely different experience. In fact, Cray is selling them and there is one on the TOP500 list, so I am pretty sure Arm is ready to become relevant.

> we should consider dropping the tests for non-x86 archs

We discovered quite a few actual Espresso bugs during the porting and will likely continue to do so in maintaining support. Even if you don't care about the architecture, I think it provides similar (but disjoint) benefits as the clang-analyzer runs do.

**Comment by fweik** [comment] 2019-04-03 13:31
Instead of disabling the tests altogether, we could also limit the test set to those tests that reliably don't timeout. If possible at all I'd also like to keep the multi-arch tests.

**Comment by RudolfWeeber** [comment] 2019-04-03 13:41
On Wed, Apr 03, 2019 at 06:31:54AM -0700, Florian Weik wrote:
> Instead of disabling the tests altogether, we could also limit the test set to those tests that reliably don't timeout. If possible at all I'd also like to keep the multi-arch tests.
Id be happy with that solution. They only misdirect attention, if they cause false positives.

**Comment by mkuron** [comment] 2019-04-03 14:00
Shouldn't we rather make the tests run faster or figure out why they sometimes are too slow?

**Comment by RudolfWeeber** [comment] 2019-04-03 14:25
#2641

On Wed, Apr 03, 2019 at 07:00:44AM -0700, Michael Kuron wrote:
> Shouldn't we rather make the tests run faster or figure out why they sometimes are too slow?
I did that for the ones, where it was easily possible.
The Stokes sphere (if we keep it) will also get better with #2633, at least it did for clang:6.0.
If you can come up with better solutions for the remaining long-running ones, they can be removed from the blacklist again.

**Comment by fweik** [comment] 2019-04-04 11:07
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/92358

Just to be clear, this does affect all platforms and is not limited to gpu tests.

**Comment by fweik** [comment] 2019-04-04 16:21
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/92670

**Comment by fweik** [comment] 2019-04-08 18:58
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/93891

**Comment by fweik** [comment] 2019-04-11 22:31
This issue is persisting: https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/96968

**Closed as completed** 2019-07-03 09:28 UTC
Labels: DevOps
