### ISSUE TITLE
Loss of precision in ScriptInterface

### ISSUE THREAD

**Issue by bindgens1** [espressomd/espresso#2396] opened 2018-12-03 14:39 UTC
@pdebuyl

During the introduction of the Lees Edwards boundary conditions, we discovered a serious issue with the ScriptInterface. This issue is of critical importance as it leads to ballooning errors and has widespread effects.

The "double" floating point parameters set via "set_params" are rounded to "float" with a relative accuracy of about 10e-8 / 10e-9. This is not only a problem with regard to Lees Edwards boundary conditions, but probably affects all parts of the code using the ScriptInterface. This includes basic components of the code like the MD timestep and system.time or the collision detection, as we show below (tested with current python branch).

```py
from __future__ import print_function
import espressomd as md
from espressomd.interactions import HarmonicBond

system = md.System(box_l=[5.0, 5.0, 5.0])
system.time_step = 0.3
system.cell_system.skin = 0.4
bond_centers = HarmonicBond(k=1000, r_0=0.0)
system.bonded_inter.add(bond_centers)
system.min_global_cut = 1.0

system.collision_detection.set_params(mode='bind_centers', distance=0.6, bond_centers=bond_centers)
print("Col Det:", system.collision_detection.distance)
```
returns:` 0.600000023842`

```py
system.integrator.run(steps=1000000)
print(system.time)
```

returns: `299999.999994`

The result is the same as explicitly casting a double to real using NumPy. For illustration:
```py
print("%20.15f" % np.array(0.6, dtype=np.float32))
```
returns: `0.600000023841858`

Exactly representable values (1, 2, 1/2, 1/4, etc) do not lose accuracy, which supports our hypothesis. Of course, a relative error of 10e-8 in the code does not impact the final outcome of a single point very much. However, this error causes rapidly increasing errors with each subsequent call, preventing consistent testing of the interface.

We understand the need to switch from globals to the ScriptInterface and were disappointed that this feature is not working as expected. The code introduced by @pdebuyl and me worked fine with global variables. We followed a very constructive and ESPResSo-conforming path for our work and updated our code to use the now-recommended ScriptInterface. However, this change resulted in a significant delay and wasted effort as we debugged our code assuming that the current ScriptInterface implementation worked properly. Our implementation of Lees-Edwards is almost complete except for this bug. 

Due to the complexity of the Cython/Boost/C++ binding, we were unable to locate the root of the problem. However, there is no obvious reason why the ScriptInterface should behave in such a way. Thus, we have no immediate view on how to solve this issue, but it is clearly of general interest for ESPResSo users and developers. This issue should be resolved as soon as possible, perhaps as early as 4.0.1, as it is not possible to rely on ScriptInterface in the current state of the code, which will hamper contributions from the userbase and lead to frustrations.

**Comment by RudolfWeeber** [comment] 2018-12-04 12:09
The behaviour of the script interface is indeed incorrect. The fix is in PR #2397.
Affected features are shapes, lb boundaries, collision detection, cluster analysis.
The MD parameters such as time step and box_l are not affected, since the script interface is not used there.

Your example for the simulation time is expected behaviour for doubles:
The error in setting the time step is of order 1E-14 for double.
Mupltiplied by 1E5 time steps, the error in the simulation time is of the order 1E-9 which is what's seen.

**Comment by bindgens1** [comment] 2018-12-04 12:38
@pdebuyl 

Thank you very much for taking care of this issue. 

As written above: The fact that we didn't suspect an error in the ScriptInterface lead to a huge waste of time on our side while trying to debug our implementation. Despite that a difference of 10e-8 won't influence most results in a big manner it is indeed really strange that none of the tests was triggered by this bug. I think that PR #2397 will fix the script interface and make it consistent with the rest of the code.

**Closed as completed** 2018-12-04 13:53 UTC

**Comment by pdebuyl** [comment] 2018-12-05 09:06
Hi @RudolfWeeber thank you for fixing this.
