### ISSUE TITLE
Irregluar failures of ICC test case on macOS

### ISSUE THREAD

**Issue by fweik** [espressomd/espresso#1207] opened 2017-06-21 11:49 UTC
The icc test case fails sometime on macOS with python3.

**Comment by mkuron** [comment] 2017-06-21 12:32
The failures on 708245595706f863f3d34ba9632fa30d23ae5d71 were due to Homebrew download issues. These appear to have been temporary and no longer occur.

The other failures are real though and seem to affect Python 2 and 3. They seem to have started at the time @KonradBreitsprecher's #1193 was merged. Some backtraces are below, but it doesn't look like a Mac-specific issue to me. Most likely, unassigned memory is used somewhere.

```
[Traviss-Mac-630:46569] *** Process received signal ***
[Traviss-Mac-630:46569] Signal: Segmentation fault: 11 (11)
[Traviss-Mac-630:46569] Signal code: Address not mapped (1)
[Traviss-Mac-630:46569] Failing at address: 0x48e8de000
[Traviss-Mac-630:46569] [ 0] 0   libsystem_platform.dylib            0x00007fff9938e52a _sigtramp + 26
[Traviss-Mac-630:46569] [ 1] 0   libfftw3.3.dylib                    0x000000010bd41b70 apply + 0
[Traviss-Mac-630:46569] [ 2] 0   libEspressoCore.4.dylib             0x000000010c4d3b51 _Z22calc_long_range_forcesv + 81
[Traviss-Mac-630:46569] [ 3] 0   libEspressoCore.4.dylib             0x000000010c4d396f _Z10force_calcv + 1423
[Traviss-Mac-630:46569] [ 4] 0   libEspressoCore.4.dylib             0x000000010c4e51dd _Z12integrate_vvii + 173
[Traviss-Mac-630:46569] [ 5] 0   libEspressoCore.4.dylib             0x000000010c4a7d72 _Z13mpi_integrateii + 66
[Traviss-Mac-630:46569] [ 6] 0   libEspressoCore.4.dylib             0x000000010c56d0c7 _Z15time_force_calci + 71
[Traviss-Mac-630:46569] [ 7] 0   libEspressoCore.4.dylib             0x000000010c53647d _ZL11p3m_mc_timePPcPiiddPdS2_S2_ + 1245
[Traviss-Mac-630:46569] [ 8] 0   libEspressoCore.4.dylib             0x000000010c534db0 _Z17p3m_adaptive_tunePPc + 1936
```

```
[Traviss-Mac-686:46641] *** Process received signal ***
[Traviss-Mac-686:46641] Signal: Segmentation fault: 11 (11)
[Traviss-Mac-686:46641] Signal code: Address not mapped (1)
[Traviss-Mac-686:46641] Failing at address: 0x7fa42b99be00
[Traviss-Mac-686:46641] [ 0] 0   libsystem_platform.dylib            0x00007fff9c23852a _sigtramp + 26
[Traviss-Mac-686:46641] [ 1] 0   ???                                 0x0000000000000358 0x0 + 856
[Traviss-Mac-686:46641] [ 2] 0   libEspressoCore.4.dylib             0x000000010563b14c _Z29calc_long_range_forces_iccp3mv + 844
[Traviss-Mac-686:46641] [ 3] 0   libEspressoCore.4.dylib             0x0000000105637f25 _Z16iccp3m_iterationv + 709
[Traviss-Mac-686:46641] [ 4] 0   libEspressoCore.4.dylib             0x000000010562b5fd _Z10force_calcv + 541
[Traviss-Mac-686:46641] [ 5] 0   libEspressoCore.4.dylib             0x000000010563d1dd _Z12integrate_vvii + 173
[Traviss-Mac-686:46641] [ 6] 0   libEspressoCore.4.dylib             0x00000001055ffd72 _Z13mpi_integrateii + 66
[Traviss-Mac-686:46641] [ 7] 0   libEspressoCore.4.dylib             0x000000010563f1b5 _Z16python_integrateibb + 837
```

```
[Traviss-Mac-685:46788] *** Process received signal ***
[Traviss-Mac-685:46788] Signal: Segmentation fault: 11 (11)
[Traviss-Mac-685:46788] Signal code: Address not mapped (1)
[Traviss-Mac-685:46788] Failing at address: 0x7fba62af5400
[Traviss-Mac-685:46788] [ 0] 0   libsystem_platform.dylib            0x00007fff9a1e752a _sigtramp + 26
[Traviss-Mac-685:46788] [ 1] 0   ???                                 0x00007fb7e263f1c0 0x0 + 140427753943488
[Traviss-Mac-685:46788] [ 2] 0   libEspressoCore.4.dylib             0x0000000101934b51 _Z22calc_long_range_forcesv + 81
[Traviss-Mac-685:46788] [ 3] 0   libEspressoCore.4.dylib             0x000000010193496f _Z10force_calcv + 1423
[Traviss-Mac-685:46788] [ 4] 0   libEspressoCore.4.dylib             0x00000001019461dd _Z12integrate_vvii + 173
[Traviss-Mac-685:46788] [ 5] 0   libEspressoCore.4.dylib             0x0000000101908d72 _Z13mpi_integrateii + 66
[Traviss-Mac-685:46788] [ 6] 0   libEspressoCore.4.dylib             0x00000001019ce0c7 _Z15time_force_calci + 71
[Traviss-Mac-685:46788] [ 7] 0   libEspressoCore.4.dylib             0x000000010199747d _ZL11p3m_mc_timePPcPiiddPdS2_S2_ + 1245
[Traviss-Mac-685:46788] [ 8] 0   libEspressoCore.4.dylib             0x0000000101995db0 _Z17p3m_adaptive_tunePPc + 1936
```

**Comment by fweik** [comment] 2017-06-21 12:37
I think the issue turned up with #1193 because this code path was not tested before. I'm currently looking into this.

**Comment by mkuron** [comment] 2017-06-23 08:39
It's some out-of-bounds access, but seems to fail only in ~20% of cases. Running it in LLDB always triggers this one first:
```
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x12e265440)
    frame #0: 0x00000001034ecf2e libEspressoCore.4.dylib`void P3M_assign_forces<6>(force_prefac=0.000050000000000000002, d_rs=1) at p3m.cpp:751
   748 	          for (i1 = 0; i1 < cao; i1++) {
   749 	            for (i2 = 0; i2 < cao; i2++) {
   750 	              p[i].f.f[d_rs] -=
-> 751 	                  force_prefac * p3m.ca_frac[cf_cnt] * p3m.rs_mesh[q_ind];
   752 	              q_ind++;
   753 	              cf_cnt++;
   754 	            }
```

I tried to use address sanitizer to see where that comes from, but that would have required me to recompile the Python interpreter and NumPy too... Were you able to reproduce the issue on Linux?

**Comment by mkuron** [comment] 2017-06-23 10:13
Allright, it seems like `p3m.ca_num` is sometimes 32, even though it should always be 224 for this test case. Unfortunately, I do not understand where in the P3M code that size is coming from.

**Comment by fweik** [comment] 2017-06-23 10:53
No I could not reproduce this. I found another issue, but I believe it is unrelated.

**Comment by fweik** [comment] 2017-06-23 15:10
The other issue was #1209, but I don't think it's related.

**Comment by mkuron** [comment] 2017-06-30 18:12
It seems like the Travis tests are passing again. Did anything change?

**Closed as completed** 2017-07-07 15:48 UTC
