### ISSUE TITLE
Checkpointing is broken

### ISSUE THREAD

**Issue by hmenke** [espressomd/espresso#1938] opened 2018-04-02 00:51 UTC
Restoring a checkpoint results in things being discarded.  Unfortunately I don't know why.

Here is a “minimal” sample script
```python
import numpy as np

import espressomd
import espressomd.checkpointing

checkpoint = espressomd.checkpointing.Checkpointing(checkpoint_id="checkpoint")

restore_point = 0
restarted = False
if checkpoint.has_checkpoints():
    restore_point = 1

# We restart the simulation loops at start_sample
start_sample = 0
checkpoint.register("start_sample")

system = espressomd.System(box_l = [10,10,10])
system.time_step = 0.01
system.cell_system.skin = 0.1

checkpoint.register("system")
checkpoint.register("system.analysis")
checkpoint.register("system.integrator") # This is suddenly necessary

if restore_point == 0:
    for i in range(100):
        system.part.add(pos=system.box_l*np.random.random(3),type=0)

checkpoint.register("system.part")

system.non_bonded_inter[0,0].lennard_jones.set_params(
        epsilon=1.0, sigma=1.0, cutoff=1.0, shift="auto")

checkpoint.register("system.non_bonded_inter")

# Warmup
if restore_point == 0:
    system.minimize_energy.init(f_max=1.0, gamma=0.01, max_steps=1000, max_displacement=0.001)
    system.minimize_energy.minimize()
    checkpoint.save(checkpoint_index=0)

system.thermostat.set_langevin(kT=1.0, gamma=6.0*np.pi)
checkpoint.register("system.thermostat")

# Equilibration
start_sample = 0
if restore_point < 2:
    if restore_point == 1:
        checkpoint.load(checkpoint_index=0)
        restarted = True

    for k in range(start_sample,1000):
        print("Equilibration: {} of {}".format(k,1000))
        print("Total = {e[total]}\n  Kinetic = {e[kinetic]}\n  Non-bonded = {e[non_bonded]}".format(e=system.analysis.energy()))
        if restarted:
            system.integrator.run(steps=1000, reuse_forces=True)
            restarted = False
        else:
            system.integrator.run(steps=1000)

        start_sample = k + 1
        checkpoint.save(checkpoint_index=0)
```
When I run this script and exit using Ctrl+C somewhere during equilibration and then restart the script, all the dynamics get lost.  As you can see, after restoring none of the energies change anymore (which shouldn't happen because there is a thermostat present).
```
Equilibration: 30 of 1000
Total = 156.155161993
  Kinetic = 155.221231061
  Non-bonded = 0.933930932133
Equilibration: 31 of 1000
Total = 129.555234977
  Kinetic = 129.322955607
  Non-bonded = 0.232279369248
Equilibration: 32 of 1000
Total = 134.164812088
  Kinetic = 133.648469798
  Non-bonded = 0.516342290276
Equilibration: 33 of 1000
Total = 149.569400416
  Kinetic = 145.355988974
  Non-bonded = 4.21341144189
Equilibration: 34 of 1000
Total = 143.221850635
  Kinetic = 142.230188836
  Non-bonded = 0.991661799032
Equilibration: 35 of 1000
Total = 152.290309356
  Kinetic = 152.020190452
  Non-bonded = 0.27011890391
^CTraceback (most recent call last):
  File "test.py", line 59, in <module>
    system.integrator.run(steps=1000)
KeyboardInterrupt
/tmp/espresso/build $ ./pypresso test.py
Equilibration: 35 of 1000
Total = 152.290309356
  Kinetic = 152.020190452
  Non-bonded = 0.27011890391
Equilibration: 36 of 1000
Total = 152.290309356
  Kinetic = 152.020190452
  Non-bonded = 0.27011890391
Equilibration: 37 of 1000
Total = 152.290309356
  Kinetic = 152.020190452
  Non-bonded = 0.27011890391
Equilibration: 38 of 1000
Total = 152.290309356
  Kinetic = 152.020190452
  Non-bonded = 0.27011890391
Equilibration: 39 of 1000
Total = 152.290309356
  Kinetic = 152.020190452
  Non-bonded = 0.27011890391
Equilibration: 40 of 1000
Total = 152.290309356
  Kinetic = 152.020190452
  Non-bonded = 0.27011890391
Equilibration: 41 of 1000
Total = 152.290309356
  Kinetic = 152.020190452
  Non-bonded = 0.27011890391
```

**Comment by hmenke** [comment] 2018-04-04 09:38
Can somebody please confirm?

**Comment by KaiSzuttor** [comment] 2018-04-04 09:59
Maybe we should try to get the testcase PR #1940 running and check more parts, i.e. also the thermostat

**Comment by KaiSzuttor** [comment] 2018-04-06 11:40
@hmenke please check PR #1940 and see if your issue is still there

**Comment by hmenke** [comment] 2018-04-08 23:03
@KaiSzuttor No change:
```
Equilibration: 23 of 1000
Total = 156.762866985
  Kinetic = 156.762866985
  Non-bonded = 0.0
Equilibration: 24 of 1000
Total = 146.16802675
  Kinetic = 146.070756582
  Non-bonded = 0.0972701685096
^CTraceback (most recent call last):
  File "test.py", line 59, in <module>
    system.integrator.run(steps=1000)
KeyboardInterrupt
/tmp/espresso/build $ ./pypresso test.py
Equilibration: 24 of 1000
Total = 146.16802675
  Kinetic = 146.070756582
  Non-bonded = 0.0972701685096
Equilibration: 25 of 1000
Total = 146.16802675
  Kinetic = 146.070756582
  Non-bonded = 0.0972701685096
Equilibration: 26 of 1000
Total = 146.16802675
  Kinetic = 146.070756582
  Non-bonded = 0.0972701685096
```
Just for reference:
```cpp
/tmp/espresso/build $ cat myconfig.hpp | grep -E '^#'
#define EXTERNAL_FORCES
#define CONSTRAINTS
#define LB_GPU
#define LB_BOUNDARIES_GPU
#define LENNARD_JONES_GENERIC
```

**Comment by KaiSzuttor** [comment] 2018-04-09 13:51
``` python
import espressomd.checkpointing

checkpoint = espressomd.checkpointing.Checkpointing(checkpoint_id="mycheckpoint")

system = espressomd.System(box_l=[10.0]*3)
checkpoint.register("system")                                                    
if (not checkpoint.has_checkpoints()):
    print("Starting from scratch")
    system.cell_system.skin = 0.4
    system.time_step = 0.01
    system.thermostat.set_langevin(kT=1.0, gamma=20.0)
    system.part.add(pos=[1.0, 2.0, 3.0])
else:
    print("Starting from checkpoint")
    checkpoint.load(0)

for i in range(5):
    system.integrator.run(10)
    print(system.analysis.energy())

checkpoint.save(0)

```

gives the following output:
First run:
``` bash
Starting from scratch
OrderedDict([('total', 1.463880510487304), ('kinetic', 1.463880510487304), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0), (('dipolar', 0), 0.0), ('dipolar', 0.0)])
OrderedDict([('total', 1.8765115110001316), ('kinetic', 1.8765115110001316), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0), (('dipolar', 0), 0.0), ('dipolar', 0.0)])
OrderedDict([('total', 0.17292512501054244), ('kinetic', 0.17292512501054244), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0), (('dipolar', 0), 0.0), ('dipolar', 0.0)])
OrderedDict([('total', 1.2821356534319919), ('kinetic', 1.2821356534319919), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0), (('dipolar', 0), 0.0), ('dipolar', 0.0)])
OrderedDict([('total', 0.8925516328343559), ('kinetic', 0.8925516328343559), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0), (('dipolar', 0), 0.0), ('dipolar', 0.0)])
```
Second run:
``` bash
Starting from checkpoint
OrderedDict([('total', 1.7038847470728646), ('kinetic', 1.7038847470728646), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0), (('dipolar', 0), 0.0), ('dipolar', 0.0)])
OrderedDict([('total', 1.8712017844254933), ('kinetic', 1.8712017844254933), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0), (('dipolar', 0), 0.0), ('dipolar', 0.0)])
OrderedDict([('total', 0.1733777990608723), ('kinetic', 0.1733777990608723), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0), (('dipolar', 0), 0.0), ('dipolar', 0.0)])
OrderedDict([('total', 1.2823072298908722), ('kinetic', 1.2823072298908722), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0), (('dipolar', 0), 0.0), ('dipolar', 0.0)])
OrderedDict([('total', 0.8925774293389821), ('kinetic', 0.8925774293389821), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0), (('dipolar', 0), 0.0), ('dipolar', 0.0)])
```

**Comment by hmenke** [comment] 2018-04-18 02:07
I have adapted my example to your reduced syntax but it's not fixed.  What am I doing wrong here?
```python
import numpy as np

import espressomd
import espressomd.checkpointing

checkpoint = espressomd.checkpointing.Checkpointing(checkpoint_id="checkpoint")

restore_point = 0
restarted = False
if checkpoint.has_checkpoints():
    restore_point = 1

# We restart the simulation loops at start_sample
start_sample = 0
checkpoint.register("start_sample")

system = espressomd.System(box_l = [10,10,10])
system.time_step = 0.01
system.cell_system.skin = 0.1

checkpoint.register("system")

if restore_point == 0:
    for i in range(100):
        system.part.add(pos=system.box_l*np.random.random(3),type=0)

    system.non_bonded_inter[0,0].lennard_jones.set_params(
        epsilon=1.0, sigma=1.0, cutoff=1.0, shift="auto")

    # Warmup
    system.minimize_energy.init(f_max=1.0, gamma=0.01, max_steps=1000, max_displacement=0.001)
    system.minimize_energy.minimize()
    checkpoint.save(checkpoint_index=0)

    system.thermostat.set_langevin(kT=1.0, gamma=6.0*np.pi)

# Equilibration
start_sample = 0
if restore_point < 2:
    if restore_point == 1:
        checkpoint.load(checkpoint_index=0)
        restarted = True

    for k in range(start_sample,1000):
        print("Equilibration: {} of {}".format(k,1000))
        print("Total = {e[total]}\n  Kinetic = {e[kinetic]}\n  Non-bonded = {e[non_bonded]}".format(e=system.analysis.energy()))
        if restarted:
            system.integrator.run(steps=1000, reuse_forces=True)
            restarted = False
        else:
            system.integrator.run(steps=1000)

        start_sample = k + 1
        checkpoint.save(checkpoint_index=0)
```

```
Equilibration: 14 of 1000
Total = 147.06391299
  Kinetic = 141.69516946
  Non-bonded = 5.36874353018
Equilibration: 15 of 1000
Total = 141.213625789
  Kinetic = 141.213625789
  Non-bonded = 0.0
^CTraceback (most recent call last):
  File "test.py", line 51, in <module>
    system.integrator.run(steps=1000)
KeyboardInterrupt
/tmp/espresso/build $ ./pypresso test.py
Equilibration: 15 of 1000
Total = 141.213625789
  Kinetic = 141.213625789
  Non-bonded = 0.0
Equilibration: 16 of 1000
Total = 141.213625789
  Kinetic = 141.213625789
  Non-bonded = 0.0
Equilibration: 17 of 1000
Total = 141.213625789
  Kinetic = 141.213625789
  Non-bonded = 0.0
```

**Comment by hmenke** [comment] 2018-04-18 02:16
Actually, your example doesn't work for me either.
```
/tmp/espresso/build $ ./pypresso test.py
Starting from scratch
OrderedDict([('total', 1.463880510487304), ('kinetic', 1.463880510487304), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0)])
OrderedDict([('total', 1.8765115110001316), ('kinetic', 1.8765115110001316), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0)])
OrderedDict([('total', 0.17292512501054244), ('kinetic', 0.17292512501054244), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0)])
OrderedDict([('total', 1.2821356534319919), ('kinetic', 1.2821356534319919), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0)])
OrderedDict([('total', 0.8925516328343559), ('kinetic', 0.8925516328343559), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0)])
/tmp/espresso/build $ ./pypresso test.py
Starting from checkpoint
OrderedDict([('total', 0.8925516328343561), ('kinetic', 0.8925516328343561), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0)])
OrderedDict([('total', 0.8925516328343561), ('kinetic', 0.8925516328343561), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0)])
OrderedDict([('total', 0.8925516328343561), ('kinetic', 0.8925516328343561), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0)])
OrderedDict([('total', 0.8925516328343561), ('kinetic', 0.8925516328343561), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0)])
OrderedDict([('total', 0.8925516328343561), ('kinetic', 0.8925516328343561), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0)])
```
For what it's worth
```
/tmp/espresso/build $ grep "^#" myconfig.hpp
#define EXTERNAL_FORCES
#define CONSTRAINTS
#define LB_GPU
#define LB_BOUNDARIES_GPU
#define LENNARD_JONES_GENERIC
/tmp/espresso/build $ git show HEAD
commit c231bce1b203ff8c6f35a5e9f92a2d3183d13065 (HEAD -> python, origin/python, origin/HEAD)
Merge: 2abdd54 c3a9f36
Author: Florian Weik <florianweik@gmail.com>
Date:   Mon Apr 16 18:28:33 2018 +0200

    Merge pull request #1951 from RudolfWeeber/steepest_descent
    
    Core: no lb propagation and collision detection during steepest descent
```
Addendum: It also doesn't work with `maxset.hpp`.

**Comment by KaiSzuttor** [comment] 2018-04-18 08:45
I've just built the same commit with the same features enabled and cannot reproduce your issue. Please don't mark an issue as a bug if its not confirmed.

**Comment by KaiSzuttor** [comment] 2018-04-18 08:49
``` python
python -c 'import pickle; print pickle.__version__'
```
gives
```
$Revision: 72223 $
```
Maybe check that?

**Comment by KaiSzuttor** [comment] 2018-04-18 08:50
BTW, we now have tests with the docker container, please try it with one of those and if it works compare your system with the container system.

**Comment by AlexanderDKazakov** [comment] 2018-04-18 15:28
Can it be connected with python version? I have python 2.7.14 and I have the same issue as @hmenke has. What python version do you have?


Now I have compiled the last commit. Here output (I added system.time as well):
```
./ipy_2018_4_18 chk.py
Starting from scratch
OrderedDict([('total', 1.463880510487304), ('kinetic', 1.463880510487304), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0)])
('TIME:', 0.09999999999999999)
OrderedDict([('total', 1.8765115110001316), ('kinetic', 1.8765115110001316), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0)])
('TIME:', 0.20000000000000004)
OrderedDict([('total', 0.17292512501054244), ('kinetic', 0.17292512501054244), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0)])
('TIME:', 0.3000000000000001)
OrderedDict([('total', 1.2821356534319919), ('kinetic', 1.2821356534319919), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0)])
('TIME:', 0.4000000000000002)
OrderedDict([('total', 0.8925516328343559), ('kinetic', 0.8925516328343559), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0)])
('TIME:', 0.5000000000000002)

./ipy_2018_4_18 chk.py
Starting from checkpoint
OrderedDict([('total', 0.8925516328343561), ('kinetic', 0.8925516328343561), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0)])
('TIME:', 0.5000000000000002)
OrderedDict([('total', 0.8925516328343561), ('kinetic', 0.8925516328343561), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0)])
('TIME:', 0.5000000000000002)
OrderedDict([('total', 0.8925516328343561), ('kinetic', 0.8925516328343561), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0)])
('TIME:', 0.5000000000000002)
OrderedDict([('total', 0.8925516328343561), ('kinetic', 0.8925516328343561), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0)])
('TIME:', 0.5000000000000002)
OrderedDict([('total', 0.8925516328343561), ('kinetic', 0.8925516328343561), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0)])
('TIME:', 0.5000000000000002)
```
```
python -c 'import pickle; print pickle.__version__' gives to me:
$Revision: 72223 $
```

**Comment by KaiSzuttor** [comment] 2018-04-19 07:14
I have just checked with python version 2.7.14 and did not had the issue. So it doesn't seem to be related to the python version.

**Comment by hmenke** [comment] 2018-04-19 11:34
Python 2.7.12 and pickle 72223 here (Ubuntu 16.04 LTS https://packages.ubuntu.com/xenial-updates/python).

**Comment by AlexanderDKazakov** [comment] 2018-04-19 15:54
I build espresso using Docker. Checkpointing is working as expected. It is weird.

**Comment by pdebuyl** [comment] 2018-04-20 12:54
Ubuntu 16.04 LTS, Python 3.5.2, no issue as far as I can tell.

```
(md_env) pierre.db@itf50:/pierre/code/espresso/build$ ./pypresso issue_1938.py 
Equilibration: 0 of 1000
Total = 0.0
  Kinetic = 0.0
  Non-bonded = 0.0
Equilibration: 1 of 1000
Total = 151.4534202479166
  Kinetic = 149.60196353483366
  Non-bonded = 1.851456713082933
Equilibration: 2 of 1000
Total = 132.96864004838648
  Kinetic = 131.9243881799334
  Non-bonded = 1.044251868453065
Equilibration: 3 of 1000
Total = 152.92638761999538
  Kinetic = 150.75509424327728
  Non-bonded = 2.1712933767181104
Equilibration: 4 of 1000
Total = 159.08598778949917
  Kinetic = 158.81045729738537
  Non-bonded = 0.2755304921137931
^CTraceback (most recent call last):
  File "issue_1938.py", line 62, in <module>
    checkpoint.save(checkpoint_index=0)
  File "/pierre/code/espresso/build/src/python/espressomd/checkpointing.py", line 184, in save
    pickle.dump(checkpoint_data, checkpoint_file, -1)
  File "particle_data.pyx", line 1809, in espressomd.particle_data.ParticleList.__getstate__
  File "particle_data.pyx", line 1122, in espressomd.particle_data.ParticleHandle.rotation.__get__
  File "utils.pyx", line 190, in espressomd.utils.array_locked.__new__
  File "/pierre/code/espresso/build/md_env/lib/python3.5/site-packages/numpy/core/numeric.py", line 424, in asarray
    def asarray(a, dtype=None, order=None):
KeyboardInterrupt
(md_env) pierre.db@itf50:/pierre/code/espresso/build$ ./pypresso issue_1938.py 
Equilibration: 4 of 1000
Total = 159.08598778949911
  Kinetic = 158.8104572973853
  Non-bonded = 0.2755304921137931
Equilibration: 5 of 1000
Total = 151.6320813542665
  Kinetic = 148.4193343247675
  Non-bonded = 3.2127470294989875
Equilibration: 6 of 1000
Total = 143.79458732467947
  Kinetic = 141.97967002334784
  Non-bonded = 1.8149173013316426
Equilibration: 7 of 1000
Total = 160.77788123738512
  Kinetic = 160.77788123738512
  Non-bonded = 0.0
Equilibration: 8 of 1000
Total = 158.33319299467857
  Kinetic = 157.37132009810594
  Non-bonded = 0.9618728965726424
Equilibration: 9 of 1000
Total = 145.79647827378798
  Kinetic = 145.59974179775
  Non-bonded = 0.19673647603797395
Equilibration: 10 of 1000
Total = 155.65124059646104
  Kinetic = 155.1911595655076
  Non-bonded = 0.4600810309534351
^CTraceback (most recent call last):
  File "issue_1938.py", line 59, in <module>
    system.integrator.run(steps=1000)
KeyboardInterrupt
(md_env) pierre.db@itf50:/pierre/code/espresso/build$ 
```

**Comment by hmenke** [comment] 2018-04-25 07:30
I have tried with a fresh clone from GitHub and `maxset.hpp`, to make sure that it wasn't due to my build directory being polluted but it still doesn't work.  Here is the output of `cmake -LAH .` to see all the variables: https://hastebin.com/raw/zuxahizazi
As already noted, I'm on Ubuntu 16.04 LTS with compilers and libraries from the official repos.

Addendum: I compared my installed versions of the packages with the ones in the container and they are all the same.  I compiled in the container and ran locally and it doesn't work.  I compiled in the container and ran in the container and it doesn't work.  **This is definitely a bug.**  The only thing that is left which could be causing it now is my version of Docker (1.13.1, build 092cba3) or my version of the kernel (4.4.0-116-generic).

**Comment by fweik** [comment] 2018-04-25 11:07
That it does not work in docker is really odd. Can you tell me the exact container (hash) you used?

**Comment by hmenke** [comment] 2018-04-26 01:23
@fweik 
```
$ sudo docker images espressomd/espresso-ubuntu
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
espressomd/espresso-ubuntu   latest              ec60420b9795        5 weeks ago         1.31 GB
```
That's the latest of tag `latest` (just pulled yesterday).  Here is the [DockerHub build log](https://hub.docker.com/r/espressomd/espresso-ubuntu/builds/b7l9cditk4aqlg3eccjgrgg/).

**Comment by fweik** [comment] 2018-04-26 10:31
I can reproduce the issue in docker, here is the log:

```
fweik@eldi ~/Source/espresso/build (git)-[lattice] % docker images 
REPOSITORY                   TAG                 IMAGE ID            CREATED             SIZE
espressomd/espresso-ubuntu   latest              ec60420b9795        5 weeks ago         1.31GB
fweik@eldi ~/Source/espresso/build (git)-[lattice] % docker run -u espresso -it espressomd/espresso-ubuntu:latest /bin/bash

espresso@ef87f918bb58:~$ git clone https://github.com/espressomd/espresso.git
Cloning into 'espresso'...
remote: Counting objects: 99120, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 99120 (delta 7), reused 6 (delta 1), pack-reused 99096
Receiving objects: 100% (99120/99120), 98.94 MiB | 21.75 MiB/s, done.
Resolving deltas: 100% (76839/76839), done.
Checking connectivity... done.
espresso@ef87f918bb58:~$ cd espresso/
espresso@ef87f918bb58:~/espresso$ mkdir build
espresso@ef87f918bb58:~/espresso$ cd build/
espresso@ef87f918bb58:~/espresso/build$ cat << EOF > script.py   
> import espressomd.checkpointing
> 
> checkpoint = espressomd.checkpointing.Checkpointing(checkpoint_id="mycheckpoint")
> 
> system = espressomd.System(box_l=[10.0]*3)
> checkpoint.register("system")                                                    
> if (not checkpoint.has_checkpoints()):
>     print("Starting from scratch")
>     system.cell_system.skin = 0.4
>     system.time_step = 0.01
>     system.thermostat.set_langevin(kT=1.0, gamma=20.0)
>     system.part.add(pos=[1.0, 2.0, 3.0])
> else:
>     print("Starting from checkpoint")
>     checkpoint.load(0)
> 
> for i in range(5):
>     system.integrator.run(10)
>     print(system.analysis.energy())
> 
> checkpoint.save(0)
> EOF
espresso@ef87f918bb58:~/espresso/build$ ln -s ../maintainer/configs/maxset.hpp myconfig.hpp
espresso@ef87f918bb58:~/espresso/build$ cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.7.4") 
-- Config file: /home/espresso/espresso/build/myconfig.hpp
-- Performing Test result__PRETTY_FUNCTION__
-- Performing Test result__PRETTY_FUNCTION__ - Success
CUDA_TOOLKIT_ROOT_DIR not found or specified
-- Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "7.0")
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Found Cython version 0.23
-- Found Cython: /usr/bin/cython (Required is at least version "0.23") 
-- Found NumPy: /usr/lib/python2.7/dist-packages/numpy/core/include (found version "1.11.0") 
-- NumPy ver. 1.11.0 found (include: /usr/lib/python2.7/dist-packages/numpy/core/include)
-- Found FFTW3: /usr/lib/x86_64-linux-gnu/libfftw3.so  
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/openmpi/lib/libhdf5.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found suitable version "1.8.16", minimum required is "1.8") 
-- Found PY_h5py: /usr/lib/python2.7/dist-packages/h5py  
Submodule 'libs/h5xx' (https://github.com/h5md/h5xx.git) registered for path 'libs/h5xx'
Cloning into 'libs/h5xx'...
Submodule path 'libs/h5xx': checked out '89d8d435872ec77dd931e709df98eefac8cbc925'
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- Could NOT find GSL (missing:  GSL_INCLUDE_DIR GSL_LIBRARY GSL_CBLAS_LIBRARY) 
-- Found MPI_C: /usr/lib/openmpi/lib/libmpi.so  
-- Found MPI_CXX: /usr/lib/openmpi/lib/libmpi_cxx.so;/usr/lib/openmpi/lib/libmpi.so  
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   mpi
--   serialization
--   filesystem
--   system
--   unit_test_framework
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Could NOT find Sphinx (missing:  SPHINX_EXECUTABLE SPHINX_API_DOC_EXE) (Required is at least version "1.6.6")
-- writing /home/espresso/espresso/build/myconfig-sample.hpp
-- 
-- The following features have been enabled:

 * HDF5 (required version >= 1.8) , parallel

-- The following OPTIONAL packages have been found:

 * FFTW3
 * HDF5 (required version >= 1.8) , parallel
 * Git

-- The following REQUIRED packages have been found:

 * PythonInterp
 * Cython (required version >= 0.23)
 * NumPy
 * MPI
 * Boost (required version >= 1.53.0)

-- The following OPTIONAL packages have not been found:

 * CUDA (required version >= 7.0)
 * PkgConfig
 * GSL
 * Doxygen
 * Sphinx (required version >= 1.6.6)

-- Configuring done
-- Generating done
-- Build files have been written to: /home/espresso/espresso/build
espresso@ef87f918bb58:~/espresso/build$ make -j10
[...]
[100%] Built target pypresso
espresso@ef87f918bb58:~/espresso/build$ ./pypresso script.py 
Starting from scratch
OrderedDict([('total', 1.463880510487304), ('kinetic', 1.463880510487304), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0), (('dipolar', 0), 0.0), ('dipolar', 0.0)])
OrderedDict([('total', 1.8765115110001316), ('kinetic', 1.8765115110001316), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0), (('dipolar', 0), 0.0), ('dipolar', 0.0)])
OrderedDict([('total', 0.17292512501054244), ('kinetic', 0.17292512501054244), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0), (('dipolar', 0), 0.0), ('dipolar', 0.0)])
OrderedDict([('total', 1.2821356534319919), ('kinetic', 1.2821356534319919), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0), (('dipolar', 0), 0.0), ('dipolar', 0.0)])
OrderedDict([('total', 0.8925516328343559), ('kinetic', 0.8925516328343559), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0), (('dipolar', 0), 0.0), ('dipolar', 0.0)])
espresso@ef87f918bb58:~/espresso/build$ ./pypresso script.py 
Starting from checkpoint
OrderedDict([('total', 0.8925516328343561), ('kinetic', 0.8925516328343561), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0), (('dipolar', 0), 0.0), ('dipolar', 0.0)])
OrderedDict([('total', 0.8925516328343561), ('kinetic', 0.8925516328343561), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0), (('dipolar', 0), 0.0), ('dipolar', 0.0)])
OrderedDict([('total', 0.8925516328343561), ('kinetic', 0.8925516328343561), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0), (('dipolar', 0), 0.0), ('dipolar', 0.0)])
OrderedDict([('total', 0.8925516328343561), ('kinetic', 0.8925516328343561), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0), (('dipolar', 0), 0.0), ('dipolar', 0.0)])
OrderedDict([('total', 0.8925516328343561), ('kinetic', 0.8925516328343561), ('bonded', 0.0), (('non_bonded', 0, 0), 0.0), ('non_bonded', 0.0), ('coulomb', 0.0), (('dipolar', 0), 0.0), ('dipolar', 0.0)])
espresso@ef87f918bb58:~/espresso/build$ 
```

**Comment by hmenke** [comment] 2018-04-26 10:40
You don't even need `maxset.hpp`.  The default configuration doesn't work either.

**Comment by fweik** [comment] 2018-04-26 11:02
The issue is not related to the thermostat, which is restored correctly. The system is no longer integrate after loading the checkpoint. The reason is that Integrator._method is set to None, which makes run return directly.

**Comment by fweik** [comment] 2018-04-26 11:06
So this can be fixed by adding appropriate `__setstate__` and `__getstate__` to espressomd.Integrator.

**Comment by KaiSzuttor** [comment] 2018-04-26 11:09
But why does it work for me outside of docker?

**Comment by hmenke** [comment] 2018-04-26 11:11
It might be a good idea to add an else branch throwing an exception to `run()`, such that inconsistent state is detected earlier.
https://github.com/espressomd/espresso/blob/0aad12ec6d19030045288cdea76062d53da24eeb/src/python/espressomd/integrate.pyx#L39-L70

**Comment by fweik** [comment] 2018-04-26 11:14
Doesn't work for me outside of docker either, no idea what you did. Exactly the same behaviour on my machine.
@hmenke Would be a good idea if python had switch and enums :-)

**Comment by fweik** [comment] 2018-04-26 11:16
@KaiSzuttor Can you please add the missing pickling functions to `Integrator` and extend the checkpoint test so that this is caught?

**Closed as completed** 2018-04-26 13:00 UTC
Labels: Confirmed, Bug, Python
