### ISSUE TITLE
h5md tests fails on CentOs8/aarch64

### ISSUE THREAD

**Issue by junghans** [espressomd/espresso#3266] opened 2019-10-20 14:23 UTC
From https://koji.fedoraproject.org/koji/taskinfo?taskID=38408326 with 
[details here](https://github.com/espressomd/espresso/files/3747936/build_aarch64.txt):

```
 52/135 Test #135: h5md ..........................................***Failed    0.82 sec
Traceback (most recent call last):
  File "/builddir/build/BUILD/espresso/mpich/testsuite/python/h5md.py", line 29, in <module>
    import h5py  # h5py has to be imported *after* espressomd (MPI)
  File "/usr/lib64/python3.6/site-packages/h5py/__init__.py", line 26, in <module>
    from . import _errors
ImportError: /lib64/libgomp.so.1: cannot allocate memory in static TLS block
```
which seems like an error in `h5py`, but when I setup a aarch64 env using mock (on fedora):
```
mock -r epel-8-aarch64 --init
wget https://kojipkgs.fedoraproject.org//packages/liblzf/3.6/16.el8/aarch64/liblzf-3.6-16.el8.aarch64.rpm
mock -r epel-8-aarch64 --install ./liblzf-3.6-16.el8.aarch64.rpm
wget https://kojipkgs.fedoraproject.org//packages/h5py/2.9.0/7.el8/aarch64/python3-h5py-2.9.0-7.el8.aarch64.rpm
mock -r epel-8-aarch64 --install ./python3-h5py-2.9.0-7.el8.aarch64.rpm
mock -r epel-8-aarch64 --install python3
mock -r epel-8-aarch64 --shell
```
everything seems to work
```
<mock-chroot> sh-4.4# python3
Python 3.6.8 (default, Oct  7 2019, 17:28:01)
[GCC 8.2.1 20180905 (Red Hat 8.2.1-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
>>>
<mock-chroot> sh-4.4# uname -a
Linux 2fcb252ade1b49c0ab4d5a24efea1789 5.2.17-200.fc30.x86_64 #1 SMP Mon Sep 23 13:42:32 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by jngrad** [comment] 2020-05-28 08:19
According to [Bugzilla 1722181](https://bugzilla.redhat.com/show_bug.cgi?id=1722181), `librpm` is allocating too much TLS storage. The issue is worse on aarch64/ppc64le. This issue was reported in June 2019 and is still being investigated to this day. There doesn't seem to be a way to mitigate the TLS issue from our side. Closing.

**Closed as completed by jngrad** 2020-05-28 08:19 UTC
