### ISSUE TITLE
CMake: TEST_NP needs to be sorted out

### ISSUE THREAD

**Issue by RudolfWeeber** [espressomd/espresso#3788] opened 2020-07-03 08:28 UTC
It is currently used as the number of ranks for mpi exec, but also passed as -j to ctest, which controls parallel execution of several tests.
I don't htink, this is intentional.
Suggested solution:
Introduce two variables such as:
* TEST_MAX_MPI_RANKS
* TEST_NUM_PARALLEL_RUNNERS

With this, test execution on the work stations in the dev wor flow can be accelerated by sth like
cmake -DTEST_NUM_PARALLEL_RUNNERS=6 -DTEST_MAX_MPI_RANKS=2

**Comment by RudolfWeeber** [comment] 2020-07-06 18:57
The actual issue mentioned probably needs to be resolved, because it is confusing.

The more general aim of getting a portion of tests that run very quickly is not trivial though.
This is because the importin of the Espresso module itself takes 0.6s (on an SSd at my ICP workstation).
A trace reveals that half the Python ecosystem is imported.
Among others: 
```
import collections.abc
import ctypes
import espressomd
import espressomd.lbboundaries
import featuredefs
import inspect
import itertools
import math
import numpy as np
import OpenGL.GL
import OpenGL.GLE
import OpenGL.GLU
import OpenGL.GLUT
import os
import re
import signal
import sys
import time
```

**Comment by jngrad** [comment] 2020-07-07 11:48
I think the issue is in `maintainer/CI/build_cmake.sh`, where by default `check_procs` is equal to 2. The `-j` option of ctest should be given the number of processors allowed on the runner, while `TEST_NP` should always be 4, except on the CI job with an odd number of processors. This looks like a bug to me, as we're likely only testing on 2 and 3 cores at the moment. This can be easily fixed in 4.1.3rc.

For 4.2.0 we should use a clear syntax like the one you propose with `TEST_MAX_MPI_RANKS` and `TEST_NUM_PARALLEL_RUNNERS`, with default values of 4 resp. `$(nproc)`. I would probably propose `min(16, $(nproc))` for the latter, because on ICP workstations with many cores like `lama`, running too many tests in parallel can take a lot of RAM.

Pinning runners to `ctest -j2` shouldn't be an issue. In fact, I always redefine `-j2` to `-j24` when running tests on my workstation to get the testsuite to run fast, using the `ARGS` modifier. When a MPI job is started with more ranks than available cores, the oversubscribe modifier takes effect. Here is some data on processor use for different values of `-j` when `NP_TEST` is 4:

| -j | time | %CPU | %CPU (theory) |
| --- | ---: | ---: | ---: |
| 1  | 260 sec | 10.9% | 1 / 32 = 3.12% |
| 2  | 240 sec | 12.5% | 2 / 32 = 6.25% |
| 4  | 200 sec | 13.7% | 4 / 32 = 12.5% |
| 8  | 140 sec | 22.6% | 8 / 32 = 25.0% |

**Comment by jngrad** [comment] 2020-07-07 12:25
Looks like I misunderstood the docs, `-j` actually selects the number of parallel jobs, not the number of cores:

> `-j <jobs>, --parallel <jobs>`
> Run the tests in parallel using the given number of jobs.

That explains why the CPU usage did not match the theoretical values in the table above. The following CMake logic is wrong:
https://github.com/espressomd/espresso/blob/9b62aa2bfc1eb808ad71f4640f65af93e99a2bba/cmake/unit_test.cmake#L1-L8

This means `TEST_NUM_PARALLEL_RUNNERS` should be 1 in CI. This will decrease performance when only 1 pipeline is running and improve performance when multiple pipelines are running.

**Comment by jngrad** [comment] 2020-07-07 13:45
Here's the quick fix I was thinking about for 4.1.3rc: b4675f2. I'm looking into a cleaner solution for 4.2.0. We can probably get a default value for `TEST_NUM_PARALLEL_RUNNERS` by calculating `NP / TEST_MAX_MPI_RANKS`.

I find your python trace surprising: why are the OpenGL imports present? On my workstation `lama`, a script containing only `import espressomd` takes 440 ms to run, while importing numpy takes 260 ms to run. the command `./pypresso -v test_espresso_alone.py 2>&1 | grep -P "^import 'OpenGL"` found no match.

My trace contains the subset of the espresso ecosystem that is required to be able to instantiate a `System` object (e.g. `globals`, `thermostat`, `lbboundaries`, etc.) plus a few friends like `collections` and `numpy`. These imports are due to:
https://github.com/espressomd/espresso/blob/9b62aa2bfc1eb808ad71f4640f65af93e99a2bba/src/python/espressomd/__init__.py#L25

**Comment by RudolfWeeber** [comment] 2020-07-07 14:49
I don't think this needs to go into 4.1.3.

Not sufficiently important.

 

W.r. to the trace:

```

pypresso -m trace --trace file.py 

```

 

All the imports in all the .py files in the espressomd folder are executed,
when importing espressomd.

Probably not a high priority issue, though.

**Comment by RudolfWeeber** [comment] 2020-07-07 14:51
>This means TEST_NUM_PARALLEL_RUNNERS should be 1 in CI. This will decrease performance when only 1 pipeline is running and improve performance when >multiple pipelines are running.

AFAIK, hard cpu quota limits are enforced for the runners via docker at present.

That’s probably unnecessary, once we have fixed this issue.

**Comment by jngrad** [comment] 2020-07-07 15:02
> I don't think this needs to go into 4.1.3.

Reading through the CMake logic, my impression is that we currently only run on 2 MPI ranks in both 4.1 and 4.2. If that's indeed the case, shouldn't we fix it in 4.1.3 so that 4 MPI ranks are used?

While investigating ctest with a toy example containing 8 identical tests on 4 MPI ranks, I found out that the `-j` option tries to be smart: ctest starts `N` parallel jobs such that `N * NP_TEST` is inferior or equal to the value passed to `-j`, with `N >= 1`. I think I arrived to the same conclusion last year when reworking the testsuite, but forgot to document it. I'm not sure how ctest knows how many CPU cores are used and how it ideals with the cpu quota limits on runners.

**Comment by jngrad** [comment] 2020-07-07 16:06
`./pypresso -m trace --trace import_espressomd.py 2>&1 | grep -Po ': +(import|from) .+' | sed -r 's/: +//' | sort -u | grep OpenGL` returns nothing on the dev branch on my workstation

**Comment by RudolfWeeber** [comment] 2020-10-19 08:15
Most of the slow import time is due to numpy.
Import numpy 
takes 1.6s on my workstation. Espresso only adds another 200ms.
There is nothing we can do with regards to speeding up the test suite until new system instances can be created.
Closing

**Closed as completed** 2020-10-19 08:15 UTC
