### ISSUE TITLE
samples: load_checkpoint.py is missing a checkpoint file

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#1397] opened 2017-09-13 08:51 UTC

**Comment by davidsean** [comment] 2017-10-11 19:37
I tried merging load_checkpoint.py and save_checkpoint.py in a single file. Unfortunately, I am unable to delete the espressomd.System() class instance, which needs to be done to before since I cannot create a second one.

deleting the reference via
`system = espressomd.System()`
`del system`

doesn't seem to work, I suspect something else refers to it preventing the instance from actually being deleted. Perhaps someone who knows more about this than I do can provide some insight?

**Comment by fweik** [comment] 2017-10-11 20:22
It can't be deleted at the moment due to restrictions in the core, so what you are seeing is actually on purpose. This causes duplications in several tests but we can not fix this at the moment.

**Comment by KaiSzuttor** [comment] 2017-10-12 07:09
we could implement a clear method for the system class that removes all members and calls the init again

**Comment by fweik** [comment] 2017-10-12 07:18
There is no way to completely reset the state in the core, so there would always be unexpected behaviour.

**Comment by davidsean** [comment] 2017-10-12 10:41
I guess we can always just add a sample checkpoint file then. Do we know if checkpoint files are compatible across platforms and python versions?

**Comment by RudolfWeeber** [comment] 2018-04-02 14:23
Fix has been merged

**Closed as completed** 2018-04-02 14:23 UTC
