### ISSUE TITLE
More init issues..

### ISSUE THREAD

**Issue by HaoZeke** [espressomd/espresso#746] opened 2016-07-21 14:44 UTC
With the latest git version, {latest commit c8b61eb903af6c50ad26a606df22334959e751c9 according to git log}
compiled with the following steps

```
mkdir build 
cd build 
cmake ..
```
The tcl interface works fine, but the python version throws the following error..
This was also reproduced by using the older autotools build..
```
make distclean
./bootstrap.sh
./configure --with-python
make
```
```
./pypresso                 
Python 2.7.12 (default, Jun 28 2016, 08:31:05) 
[GCC 6.1.1 20160602] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import espressomd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/haozeke/Github/espresso/espressomd/__init__.py", line 23, in <module>
    import espressomd._init
ImportError: dynamic module does not define init function (init_init)
>>> exit()

```

**Comment by KaiSzuttor** [comment] 2016-07-22 11:47
in case of cmake, did you perform the actual compilation with <code>make</code>?

**Comment by HaoZeke** [comment] 2016-07-22 22:50
Yeah, sorry, forgot to add that..
make works but the python error is still there

**Comment by fweik** [comment] 2016-07-22 22:52
Can you please provide the cmake log, and what plattform you are on? Can you please clone a fresh repro and check if the issue remains? I could not reproduce on serveral versions of ubuntu.

**Comment by HaoZeke** [comment] 2016-07-23 10:03
Yeah, the issue isn't reproducable on ubuntu (it's a python conflict).
I'm on archlinux which uses python3 as the default, however, since python2 is also installed it doesn't cause any errors during the build but it doesn't work either.
The issue was resolved by using python2 as the default python during the build process...
(subsequently it works without requiring the default python version to be 2)
Maybe the build process should use python2 explicitly instead of calling python?

**Comment by KaiSzuttor** [comment] 2016-07-23 11:37
Maybe we should make the code python3 compatible?

**Comment by HaoZeke** [comment] 2016-07-23 21:22
That might be a rather large undertaking, I'm sure there are already reasons why the code is in python2...... besides which, arch and some systems aside, debian based OS's still default to python2

**Comment by fweik** [comment] 2016-08-02 16:25
The python version issue should be fixed by 48de16fb348c08226f010dc3c1586c6b828c535f,
can you please check? Otherwise I will close the issue.
Python3 compatibility may not be so easy because of cython.

**Comment by mkuron** [comment] 2016-08-02 16:29
Cython is supposed to support Python 3.2 and higher just fine. I don't think there is anything left that wouldn't work with Python 3, except for the Mayavi live visualization because the VTK library still only works with Python 2. Maybe we can try adding Python 3 support on a future coding day, shouldn't be too difficult.

**Comment by KaiSzuttor** [comment] 2016-08-06 19:35
I think this issue can be closed. I opened a new one as a todo for the next coding day. #780

**Closed** 2016-08-06 20:04 UTC
