### ISSUE TITLE
memory leak while piping to Espresso 

### ISSUE THREAD

**Issue by helvrud** [espressomd/espresso#1076] opened 2017-04-05 09:26 UTC
I am sending the commands to Espresso using pipe, like "cat filename.tcl | Espresso"
A also run the file using normal way "Espresso fileneame.tcl".
It works normal in second case and the memory used by Espresso is constant  155 Mb
But in the first case (by using pipe) the memory grows until Espresso gets killed by oom killer.
A test input file is included 
[test.txt](https://github.com/espressomd/espresso/files/895753/test.txt)

**Comment by hmenke** [comment] 2017-04-06 09:02
I cannot reproduce this with the latest master compiled with `maxset.hpp` and the sample input you sent.  For neither variant of the call does `valgrind` report any memory leaks (apart from some verified false positives in OpenMPI and the TCL interpreter).

**Comment by hmenke** [comment] 2017-04-10 23:35
Please add detailed instructions on how to reproduce.  I am closing this for now.

**Closed as completed by hmenke** 2017-04-10 23:35 UTC
