### ISSUE TITLE
HIP issue list as discussed in the offline meeting

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#2973] opened 2019-07-05 10:01 UTC
* https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/134161 (connected to #2878)
  unreadable error message at runtime

**Comment by KaiSzuttor** [comment] 2019-07-23 07:45
* https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/137077

**Comment by mkuron** [comment] 2019-07-23 08:15
> https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/134161

That one was due to incorrect `#pragma unroll` use and caused reduced performance (but no crash) on CUDA too.

> https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/137077

That's an odd one. We had the same error two months ago (https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/117521), but after two retries it succeeded (https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/117637). This is somehow due to a name collision between `std`, `Utils` and `<cmath>`.

**Comment by mkuron** [comment] 2019-07-23 08:26
> https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/134161

That one was due to incorrect `#pragma unroll` use and caused reduced performance (but no crash) on CUDA too. Fixed by #2982.

> https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/137077

Please merge the latest master branch, that issue has been fixed since #2937.

**Comment by mkuron** [comment] 2019-07-31 15:10
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/142467

That one was reproducible on an Nvidia 2080, but we don't have that in CI. So one more case where AMD actually helped find a bug that can affect Nvidia too.

**Comment by jngrad** [comment] 2019-12-13 15:34
* `Memory access fault by GPU node-4 (Agent handle: 0x55be70acd450) on address 0x7f70b50ec000. Reason: Page not present or supervisor privilege.`
   * https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/191997
   * https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/191285

**Comment by jngrad** [comment] 2020-03-12 16:15
The ROCm library rocFFT broke on multiple occasions:
* ROCm 2.9: espressomd/docker#139, had to write a complex fix and wait for a patch upstream
* ROCm 3.0: espressomd/docker#157, url in `/etc/apt/sources.list.d/rocm.list` was wrong
* ROCm 3.1: espressomd/docker#156, we have to wait for a patch upstream

**Comment by fweik** [comment] 2020-04-01 11:04
https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/218922

**Comment by mkuron** [comment] 2020-04-01 11:14
> https://gitlab.icp.uni-stuttgart.de/espressomd/espresso/-/jobs/218922

That's an odd one. Why does that test even call into HIP code?

```
       Start   1: save_checkpoint_lb.cpu-p3m.cpu-lj-therm.lb_1
  1/149 Test   #1: save_checkpoint_lb.cpu-p3m.cpu-lj-therm.lb_1 ..............***Exception: Child aborted  1.33 sec
Memory access fault by GPU node-5 (Agent handle: 0x563058748d20) on address 0x7f94057e0000. Reason: Page not present or supervisor privilege.
```

**Comment by jngrad** [comment] 2020-04-01 17:41
It happened again today, dedicated ticket: #3620

**Comment by fweik** [comment] 2020-04-01 18:49
@mkuron I think the gpu initialization code if always run, to detect the devices present and so on, but I haven't checked.

**Comment by mkuron** [comment] 2020-04-02 08:25
ROCm 3.3 was released last night (not sure what happened to 3.2). It's installed for testing on lama. It's still broken in multiple ways:

- `ln -s /opt/rocm/bin/hcc* /opt/rocm/hip/bin/` required because the `hipcc_cmake_linker_helper` has not been fixed.
- tests succeed, but hang during `HSA::hsa_shut_down()`

At least they fixed the `cudaMemcpyToSymbol` thing that broke the EK and LB tests. The shutdown thing is probably our own fault though; it is probably related to the order of destruction for static/global variables and library unloading.

**Comment by jngrad** [comment] 2020-09-16 14:58
* #3895 took me 5 man-hours to troubleshoot, and probably as much for @mkuron; we ended up using `lama` as a runner in CI

**Comment by mkuron** [comment] 2020-09-16 15:34
> #3895 

No idea about that one, it's either a hardware or driver issue, and a heisenbug too. We don't have anyone here who understands the Barnes-Hut code, so our debugging abilities are rather limited.

**Comment by jngrad** [comment] 2020-09-23 21:38
* #3909 broken AMD packages on `lama`, fixed by re-installing packages

**Comment by jngrad** [comment] 2020-10-16 12:52
* the `lama` backup broke down several times before, during and after the summer school (Sep 30, twice on Oct 6, Oct 12), putting us in a situation where CI could not pass and PRs could not get merged

**Comment by mkuron** [comment] 2020-10-16 13:51
> lama

The first two cases were a due to a broken SSD, the other one was due to a crashed graphics driver.

**Comment by KaiSzuttor** [comment] 2020-10-19 06:55
as long as we do not have redundancy for testing rocm, we cannot use it in CI.

**Closed as completed** 2020-10-23 08:06 UTC
