### ISSUE TITLE
Building Espresso: Cython fails with "NameError: name 'pattern' is not defined"

### ISSUE THREAD

**Issue by nagarajankarthik** [espressomd/espresso#3537] opened 2020-02-24 06:11 UTC
Dear all,

I encountered the following error when trying to build version 4.0 of Espresso:
```
Error compiling Cython file:
------------------------------------------------------------
...
    for i in range(len(len_dims)):
        c_len_dims.push_back(len_dims[i])
    cdef int c_n_dims = n_dims
    cdef int c_flattened_index = flattened_index
    cdef vector[int] unravelled_index_out
    unravelled_index_out.assign(n_dims, 0)
                              ^
------------------------------------------------------------

/home/projects/11000933/karthik/espresso/src/python/espressomd/utils.pyx:298:31: Compiler crash in AnalyseExpressionsTransform

ModuleNode.body = StatListNode(utils.pyx:19:0)
StatListNode.stats[16] = StatListNode(utils.pyx:272:0)
StatListNode.stats[0] = DefNode(utils.pyx:272:0,
    doc = '\n    Getting the unraveled index for a given flattened index in ``n_dims`` dimensions.\n\n    Parameters\n    ----------\n    len_dims : array_like :obj:`int`\n               The length of each of the ``n_dims`` dimensions.\n    n_dims : :obj:`int`\n             The number of dimensions.\n    flattened_index : :obj:`int`\n                      The flat index that should be converted back to an\n                      ``n_dims`` dimensional index.\n\n    Returns\n    -------\n    unravelled_index : array_like :obj:`int`\n                       An array containing the index for each dimension.\n\n    ',
    is_cyfunction = True,
    modifiers = [...]/0,
    name = 'get_unravelled_index',
    num_required_args = 3,
    py_wrapper_required = True,
    reqd_kw_flags_cname = '0',
    used = True)
File 'Nodes.py', line 430, in analyse_expressions: StatListNode(utils.pyx:273:4,
    is_terminator = True)
File 'Nodes.py', line 4746, in analyse_expressions: ExprStatNode(utils.pyx:298:31)
File 'ExprNodes.py', line 519, in analyse_expressions: SimpleCallNode(utils.pyx:298:31,
    analysed = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 5132, in analyse_types: SimpleCallNode(utils.pyx:298:31,
    analysed = True,
    use_managed_ref = True)
File 'ExprNodes.py', line 5187, in analyse_c_function_call: SimpleCallNode(utils.pyx:298:31,
    analysed = True,
    use_managed_ref = True)

Compiler crash traceback from this point on:
  File "/app/python/3.5.1/lib/python3.5/site-packages/Cython/Compiler/ExprNodes.py", line 5187, in analyse_c_function_call
    [arg.type for arg in args], alternatives, self.pos, env, args)
  File "/app/python/3.5.1/lib/python3.5/site-packages/Cython/Compiler/PyrexTypes.py", line 4083, in best_match
    errors.append((func, "Unable to deduce type parameters for %s given %s" % (pattern.type, actual)))
NameError: name 'pattern' is not defined
make[2]: *** [src/python/espressomd/utils.cpp] Error 1
make[2]: *** Deleting file `src/python/espressomd/utils.cpp'
make[1]: *** [src/python/espressomd/CMakeFiles/utils.dir/all] Error 2
make: *** [all] Error 2
```

May I know what could be the source of the problem?

**Comment by KaiSzuttor** [comment] 2020-02-24 08:21
In order to be able to help you we need  some more information like the cython version and the compiler you are using.

**Comment by nagarajankarthik** [comment] 2020-02-24 08:46
Hi,

I am using Cython version 0.25.2,python/3.5.1,and the gcc/5.1.0 compiler.
The Linux version is Red Hat Enterprise Linux Server release 6.10 (Santiago). Please let me know if any other information is required. Thank you for your help.

**Comment by nagarajankarthik** [comment] 2020-02-24 09:24
I have also tried to build the latest version, 4.1. I got the following error message:
```
In file included from /app/boost/1.60.0/xe_2016/parallel/include/boost/range/iterator_range.hpp:13:0,
                 from /home/projects/11000933/karthik/espresso41/src/core/Cell.hpp:26,
                 from /home/projects/11000933/karthik/espresso41/src/core/ParticleRange.hpp:22,
                 from /home/projects/11000933/karthik/espresso41/src/core/electrostatics_magnetostatics/icc.hpp:58,
                 from /home/projects/11000933/karthik/espresso41/src/core/electrostatics_magnetostatics/icc.cpp:27:
/app/boost/1.60.0/xe_2016/parallel/include/boost/range/iterator_range_core.hpp: In instantiation of 'boost::iterator_range_detail::iterator_range_base<IteratorT, TraversalTag>::iterator_range_base(Iterator, Iterator) [with Iterator = __gnu_cxx::__normal_iterator<Cell**, std::vector<Cell*, std::allocator<Cell*> > >; IteratorT = __gnu_cxx::__normal_iterator<Cell**, std::vector<Cell*, std::allocator<Cell*> > >; TraversalTag = boost::iterators::incrementable_traversal_tag]':
/app/boost/1.60.0/xe_2016/parallel/include/boost/range/iterator_range_core.hpp:312:32:   required from 'boost::iterator_range_detail::iterator_range_base<IteratorT, boost::iterators::bidirectional_traversal_tag>::iterator_range_base(Iterator, Iterator) [with Iterator = __gnu_cxx::__normal_iterator<Cell**, std::vector<Cell*, std::allocator<Cell*> > >; IteratorT = __gnu_cxx::__normal_iterator<Cell**, std::vector<Cell*, std::allocator<Cell*> > >]'
/app/boost/1.60.0/xe_2016/parallel/include/boost/range/iterator_range_core.hpp:381:32:   required from 'boost::iterator_range_detail::iterator_range_base<IteratorT, boost::iterators::random_access_traversal_tag>::iterator_range_base(Iterator, Iterator) [with Iterator = __gnu_cxx::__normal_iterator<Cell**, std::vector<Cell*, std::allocator<Cell*> > >; IteratorT = __gnu_cxx::__normal_iterator<Cell**, std::vector<Cell*, std::allocator<Cell*> > >]'
/app/boost/1.60.0/xe_2016/parallel/include/boost/range/iterator_range_core.hpp:483:40:   required from 'boost::iterator_range<IteratorT>::iterator_range(Iterator, Iterator) [with Iterator = __gnu_cxx::__normal_iterator<Cell**, std::vector<Cell*, std::allocator<Cell*> > >; IteratorT = __gnu_cxx::__normal_iterator<Cell**, std::vector<Cell*, std::allocator<Cell*> > >]'
/home/projects/11000933/karthik/espresso41/src/core/Cell.hpp:77:70:   required from 'Neighbors<CellRef>::cell_range Neighbors<CellRef>::red() [with CellRef = Cell*; Neighbors<CellRef>::cell_range = boost::iterator_range<__gnu_cxx::__normal_iterator<Cell**, std::vector<Cell*, std::allocator<Cell*> > > >; typename std::vector<_RealType>::iterator = __gnu_cxx::__normal_iterator<Cell**, std::vector<Cell*, std::allocator<Cell*> > >]'
/home/projects/11000933/karthik/espresso41/src/core/algorithm/link_cell.hpp:47:7:   required from 'void Algorithm::link_cell(CellIterator, CellIterator, ParticleKernel&&, PairKernel&&, DistanceFunction&&) [with CellIterator = boost::iterators::indirect_iterator<Cell**, boost::iterators::use_default, boost::iterators::use_default, boost::iterators::use_default, boost::iterators::use_default>; ParticleKernel = Utils::NoOp; PairKernel = force_calc_iccp3m(const ParticleRange&, const ParticleRange&)::<lambda(Particle&, Particle&, Distance&)>; DistanceFunction = detail::EuclidianDistance]'
/home/projects/11000933/karthik/espresso41/src/core/algorithm/for_each_pair.hpp:67:14:   required from 'void Algorithm::for_each_pair(CellIterator, CellIterator, ParticleKernel&&, PairKernel&&, DistanceFunction&&, VerletCriterion&&, bool, bool) [with CellIterator = boost::iterators::indirect_iterator<Cell**, boost::iterators::use_default, boost::iterators::use_default, boost::iterators::use_default, boost::iterators::use_default>; ParticleKernel = Utils::NoOp; PairKernel = force_calc_iccp3m(const ParticleRange&, const ParticleRange&)::<lambda(Particle&, Particle&, Distance&)>; DistanceFunction = detail::EuclidianDistance; VerletCriterion = const detail::True&]'
/home/projects/11000933/karthik/espresso41/src/core/short_range_loop.hpp:79:29:   required from 'void detail::decide_distance(CellIterator, CellIterator, ParticleKernel&&, PairKernel&&, VerletCriterion&&) [with CellIterator = boost::iterators::indirect_iterator<Cell**, boost::iterators::use_default, boost::iterators::use_default, boost::iterators::use_default, boost::iterators::use_default>; ParticleKernel = Utils::NoOp; PairKernel = force_calc_iccp3m(const ParticleRange&, const ParticleRange&)::<lambda(Particle&, Particle&, Distance&)>; VerletCriterion = const detail::True&]'
/home/projects/11000933/karthik/espresso41/src/core/short_range_loop.hpp:125:28:   required from 'void short_range_loop(ParticleKernel&&, PairKernel&&, const VerletCriterion&) [with ParticleKernel = Utils::NoOp; PairKernel = force_calc_iccp3m(const ParticleRange&, const ParticleRange&)::<lambda(Particle&, Particle&, Distance&)>; VerletCriterion = detail::True]'
/home/projects/11000933/karthik/espresso41/src/core/electrostatics_magnetostatics/icc.cpp:202:4:   required from here
/app/boost/1.60.0/xe_2016/parallel/include/boost/range/iterator_range_core.hpp:218:5: internal compiler error: Segmentation fault
     }
```
As shown in the message above, the boost version is 1.60.0. Any help would be greatly appreciated!

**Comment by jngrad** [comment] 2020-02-24 09:36
The first error is actually a bug in the Cython compiler:
```
Compiler crash traceback from this point on:
  File "/app/python/3.5.1/lib/python3.5/site-packages/Cython/Compiler/ExprNodes.py", line 5187, in analyse_c_function_call
    [arg.type for arg in args], alternatives, self.pos, env, args)
  File "/app/python/3.5.1/lib/python3.5/site-packages/Cython/Compiler/PyrexTypes.py", line 4083, in best_match
    errors.append((func, "Unable to deduce type parameters for %s given %s" % (pattern.type, actual)))
NameError: name 'pattern' is not defined
```
The variable `pattern` is accessed out of scope in [PyrexTypes.py#L4078-L4083](https://github.com/cython/cython/blob/cc2abe1f895f9f9340f48732c5377befe6f21e4e/Cython/Compiler/PyrexTypes.py#L4078-L4083). This bug was introduced in Cython 0.25.x and fixed in Cython 0.26.x. You'll need to upgrade Cython to build espresso 4.0. This is reproducible on our `debian-python3:9` docker image.

**Comment by jngrad** [comment] 2020-02-24 09:56
Concerning the Intel Parallel Studio XE 2016 compiler error, we only tested the 2015 and 2017 versions using boost 1.65 and boost 1.66 on Ubuntu 14.04. There was probably a good reason to use far more recent boost versions than those available in the Ubuntu 14.04 repository, but the commit message is unhelpful (espressomd/docker@38e0cc5e31). @mkuron do you remember the reason?

**Comment by mkuron** [comment] 2020-02-24 11:52
Older Boost versions were broken in multiple ways with newer Intel compilers. Try 1.66 as a minimum.

**Comment by nagarajankarthik** [comment] 2020-02-24 12:37
@jngrad and @mkuron : Thank you for the quick reply.

I am trying to build Espresso on a High-Performance Computing (HPC) cluster for which I do not have administrative privileges. Therefore, I am unsure of the feasibility of upgrading the software required to build Espresso. My system specifications are as follows:

Red Hat Enterprise Linux Server release 6.10 (Santiago)
Boost 1.60.0
Python 3.5.1
Cython 0.25.2
GCC compiler 5.1.0
cuda 9.2
fftw 3.3.4
hdf5 1.8.17
cmake/3.8.0-rc1
INTEL MPI Library 5.1.2 Build 20151015 (build id: 13147)

May I know whether there is any existing version of Espresso which will work with the above versions of the various tools required to compile and run the source code?

**Comment by jngrad** [comment] 2020-02-26 13:35
We've only tested espresso with the Intel MPI library in combination with the Intel compiler and recent boost versions in CI. Below are the logs of manual builds with various versions of GCC/CUDA/Cython/Intel-MPI/boost. Cuda 8 to 10 are supported, GCC 4.8 to 7.4, boost 1.63 and 1.66.

I'm not sure you'll be able to compile espresso with Cython 0.25 and boost 1.60. Do you have the option of building espresso in a docker container and using that binary in your HPC environment?

espresso 4.0 cuda 8 Intel MPI 2018
```
cp ../maintainer/configs/maxset.hpp myconfig.hpp
cmake .. -DCMAKE_C_COMPILER=$(which gcc) -DCMAKE_CXX_COMPILER=$(which g++)
-- The CXX compiler identification is GNU 4.8.4
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Found CUDA: /usr/local/cuda (found suitable version "8.0", minimum required is "7.0") 
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- Found Cython version 0.29.10
-- Found MPI_CXX: /opt/intel-mpi/compilers_and_libraries_2018.1.163/linux/mpi/intel64/lib/libmpicxx.so (found version "3.1") 
-- Boost version: 1.65.0
$> make
[100%] Built target pypresso
$> make check_unit_tests
100% tests passed, 0 tests failed out of 41
```

espresso 4.1 cuda 9 Intel MPI 2018
```
cp ../maintainer/configs/maxset.hpp myconfig.hpp
cmake .. -DCMAKE_C_COMPILER=$(which gcc) -DCMAKE_CXX_COMPILER=$(which g++)
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/gcc -- works
-- Found CUDA: /usr/local/cuda (found suitable version "9.0", minimum required is "9.0") 
-- Found PythonInterp: /usr/bin/python3 (found version "3.5.2") 
-- Found Cython version 0.23.4
-- Found MPI_CXX: /opt/intel-mpi/compilers_and_libraries_2018.2.199/linux/mpi/intel64/lib/libmpicxx.so (found suitable version "3.1", minimum required is "3.0") 
-- Boost version: 1.66.0
$> make
[100%] Built target pypresso
$> make check_unit_tests
100% tests passed, 0 tests failed out of 68
```

espresso 4.1 without cuda and with boost 1.63 Intel MPI 2019
```
cp ../maintainer/configs/maxset.hpp myconfig.hpp
cmake .. -DCMAKE_C_COMPILER=$(which gcc) -DCMAKE_CXX_COMPILER=$(which g++)
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/gcc -- works
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.9")
-- Found Cython version 0.26.1
-- Found MPI_CXX: /opt/intel/compilers_and_libraries_2019.5.281/linux/mpi/intel64/lib/libmpicxx.so (found suitable version "3.1", minimum required is "3.0") 
-- Boost version: 1.63.0
$> make
[100%] Built target pypresso
$> make check_unit_tests
100% tests passed, 0 tests failed out of 68
```

espresso 4.1 cuda 10 Intel MPI 2018
```
$> cp ../maintainer/configs/maxset.hpp myconfig.hpp
$> cmake .. -DCMAKE_C_COMPILER=$(which gcc) -DCMAKE_CXX_COMPILER=$(which g++)
-- The CXX compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Found CUDA: /usr/local/cuda (found suitable version "10.0", minimum required is "9.0") 
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.8") 
-- Found Cython version 0.26.1
-- Found MPI_CXX: /opt/intel/compilers_and_libraries_2018.5.274/linux/mpi/intel64/lib/libmpicxx.so (found suitable version "3.1", minimum required is "3.0") 
-- Boost version: 1.66.0
$> make
[100%] Built target pypresso
$> make check_unit_tests
100% tests passed, 0 tests failed out of 68
```

espresso 4.1 cuda 10 Intel MPI 2019
```
$> cp ../maintainer/configs/maxset.hpp myconfig.hpp
$> cmake .. -DCMAKE_C_COMPILER=$(which gcc) -DCMAKE_CXX_COMPILER=$(which g++)
-- The CXX compiler identification is GNU 7.4.0
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Found CUDA: /usr/local/cuda (found suitable version "10.1", minimum required is "9.0") 
-- Found PythonInterp: /usr/bin/python3 (found version "3.6.9") 
-- Found Cython version 0.26.1
-- Found MPI_CXX: /opt/intel/compilers_and_libraries_2019.5.281/linux/mpi/intel64/lib/libmpicxx.so (found suitable version "3.1", minimum required is "3.0") 
-- Boost version: 1.66.0
$> make
[100%] Built target pypresso
$> make check_unit_tests
100% tests passed, 0 tests failed out of 68
```

**Comment by nagarajankarthik** [comment] 2020-02-27 02:25
I am unsure as to whether I can build Espresso in a docker container since docker does not seem to be installed in my system. I have downloaded boost 1.72. Are there any specific steps I need to take to build certain libraries?

**Comment by jngrad** [comment] 2020-02-27 07:16
This is how we build boost from sources for the Intel MPI library and set up environment variables such that the espresso CMake can find it: [espressomd/docker/intel-python3/Dockerfile-19#L47-L58](https://github.com/espressomd/docker/blob/c127f91b069acf0f07e0be155ac42799a968a3e2/docker/intel-python3/Dockerfile-19#L47-L58)

**Comment by nagarajankarthik** [comment] 2020-02-27 12:54
> This is how we build boost from sources for the Intel MPI library and set up environment variables such that the espresso CMake can find it: [espressomd/docker/intel-python3/Dockerfile-19#L47-L58](https://github.com/espressomd/docker/blob/c127f91b069acf0f07e0be155ac42799a968a3e2/docker/intel-python3/Dockerfile-19#L47-L58)

Do I need to install Docker first? From this page (https://docs.docker.com/install/linux/docker-ce/ubuntu/), it appears that would require me to have sudo privileges, which I do not have.

**Comment by jngrad** [comment] 2020-02-27 15:28
The section highlighted in yellow is standard shell syntax. Use e.g. `install --prefix=$HOME/boost` to install the compiled boost files somewhere in your home folder, and `export BOOST_ROOT=$HOME/boost`, `export LD_LIBRARY_PATH="$HOME/boost/lib:${LD_LIBRARY_PATH}"` so that CMake can find them.

**Comment by nagarajankarthik** [comment] 2020-02-28 01:41
When attempting to build Boost using the steps shown in (https://github.com/espressomd/docker/blob/c127f91b069acf0f07e0be155ac42799a968a3e2/docker/intel-python3/Dockerfile-19#L47-L58), I got numerous error messages such as the one below:

```
In file included from ./boost/python/detail/prefix.hpp(13),
                 from ./boost/python/converter/from_python.hpp(8),
                 from libs/python/src/converter/from_python.cpp(6):
./boost/python/detail/wrap_python.hpp(57): catastrophic error: cannot open source file "pyconfig.h"
  include <pyconfig.h>
```

How do I locate pyconfig.h?

**Comment by jngrad** [comment] 2020-02-28 09:11
On Fedora or Red Hat Enterprise, you'll need to install package `python3-devel` from your package manager to generate file `/usr/include/python3.*/pyconfig.h`.

**Comment by nagarajankarthik** [comment] 2020-02-28 09:56
I just tried to do that using the command 'yum install python3-devel'. But I got the following error message:

Loaded plugins: priorities, product-id, search-disabled-repos, security, subscription-manager
Error loading certificate: [Errno 13] Permission denied: '/etc/pki/entitlement/3172555776528829459.pem'
You need to be root to perform this command.


Is there a workaround for this?

**Comment by jngrad** [comment] 2020-02-28 10:55
The file `pyconfig.h` is built from `pyconfig.h.in` when installing `python3-devel`, so you can't really work around it. You'll need to consult the system administrator of the HPC center and the system administrator of your home institute to find a solution. Maybe they can setup a server with docker (if necessary using kaniko or the docker-in-docker method for improved security) or any other emulator software for you, such that you can emulate their build environment and update packages without root privileges.

**Comment by nagarajankarthik** [comment] 2020-02-28 12:11
I see. The problem is that I am presently unable to contact my system admininstrator.

Anyhow, @jngrad , many thanks for patiently answering my various questions. I guess we can close this issue for the time being.

**Closed as completed** 2020-02-28 12:11 UTC
