### ISSUE TITLE
Check if python interface can be easily made python3 compatible

### ISSUE THREAD

**Issue by KaiSzuttor** [espressomd/espresso#780] opened 2016-08-06 19:34 UTC
This is a TODO for the next coding day.

**Comment by RudolfWeeber** [comment] 2016-08-07 10:01
Cython has python 3 support. I looked through Python 3 synatx
changes and think, we aren't affected on a large scale
* We anyway don't use print (often)
* We anyway only use 7-bit strings, as it's all english.
* Exceptions already use the ValueError("messsage") syntax


I'd suggest to postpone actually doing it until there aren't any
more pressing issues for the school in October, though.

**Comment by mkuron** [comment] 2016-08-07 14:50
I'll have a look at it at the next coding day, please assign the issue to me. As we do quite regularly get bug reports that end up being caused by the lack of Python 3 support, and a number of new people will try to install Espresso on their personal and work computers after the summer school, I think it would make sense to get this fixed now.

**Comment by RudolfWeeber** [comment] 2016-08-08 09:25
Ok. Will do.

**Closed** 2016-08-30 17:28 UTC
Labels: CodingDayAugust16
